spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JTMRengl/Spring-config-1705c.git/
          search-paths: offcn/config-repo
          username: JTMRengl
          password: CuiSM19820508
server:
  port: 7001

# 配置服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:10086/eureka,http://eureka1:10087/eureka

